# src Makefile
include ../../../Makefile.common
OBJS+=SysTick_main.o
all:SysTick_main.o
.PHONY: clean tshow
clean:
	rm -f SysTick_main.o
tshow:
	@echo "######################################################################################################"
	@echo "######## optimize settings: $(InfoTextLib), $(InfoTextSrc)"
	@echo "######################################################################################################"
