# src Makefile
include ../../Makefile.common
01_LED:
	$(MAKE) -C 01_LED $@
02_SysTick:
	$(MAKE) -C 02_SysTick $@
03_USART:
	$(MAKE) -C 03_USART $@

.PHONY: clean tshow
clean:
tshow:
	@echo "######################################################################################################"
	@echo "######## optimize settings: $(InfoTextLib), $(InfoTextSrc)"
	@echo "######################################################################################################"
