# src Makefile
include ../../../Makefile.common
OBJS+=LED_main.o
all:LED_main.o
#	$(CC) $(CFLAGSLIB) LED_main.c
.PHONY: clean tshow
clean:
	rm -f LED_main.o
tshow:
	@echo "######################################################################################################"
	@echo "######## optimize settings: $(InfoTextLib), $(InfoTextSrc)"
	@echo "######################################################################################################"
